apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-1.amazonaws.com/nginx-prod:a1ea8c9c06c589014d3fd963e41e3db5b00014dc
    name: nginx
    ports:
    - containerPort: 80
    resources: 
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
      
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
