apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: voting-app
  name: voting-app
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-2.amazonaws.com/voting-app:72fa78ed94bf60e388eb121c5b30be923f01ddbe
    name: voting-app
    env:
      - name: REDIS
        value: redis-svc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
