apiVersion: v1
kind: Service
metadata:
  labels:
    run: voting-app
  name: voting-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: voting-app
  type: ClusterIP
status:
  loadBalancer: {}
