apiVersion: v1
kind: Pod
metadata:
  labels:
    run: voting-app
    tier: backend
  name: voting-app
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-1.amazonaws.com/voting-app-prod:5e16ebc41369950e5d3c89f13eed7853d9cf8a9a
    name: voting-app
    env:
      - name: REDIS
        value: redis-svc
    resources: 
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
