apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: voting-app
  name: voting-app
spec:
  containers:
  - image: 087380303747.dkr.ecr.eu-west-1.amazonaws.com/voting-app-prod:cbabaeb3ca1e4b61053f4e8e41611f72d8b1ffa7
    name: voting-app
    env:
      - name: REDIS
        value: redis-svc
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
